CREATE SCHEMA statistics;

CREATE TABLE statistics.browser(
  id SERIAL PRIMARY KEY ,
  browser TEXT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  report TIMESTAMP NOT NULL
);

CREATE TABLE statistics.country(
  id SERIAL PRIMARY KEY ,
  country TEXT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  report TIMESTAMP NOT NULL
);

CREATE TABLE statistics.url(
  id SERIAL PRIMARY KEY ,
  url TEXT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  report TIMESTAMP NOT NULL
);

CREATE TABLE statistics.day(
  id SERIAL PRIMARY KEY ,
  day TEXT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  report TIMESTAMP NOT NULL
);

CREATE TABLE statistics.time(
  id SERIAL PRIMARY KEY ,
  time TEXT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  report TIMESTAMP NOT NULL
);